##### Properties of SVD

In [2]:
import numpy as np

In [1]:
def matrix_column_l2_norm(M):
    """Returns the l2 norm of each column of matrix M, """
    return (M ** 2).sum(0)

In [3]:
# Generate random m x n matrix, M
m, n = 10, 5
np.random.seed(123)      # reproducibility
M = np.random.randn(m, n)
print(M)

[[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
 [ 1.65143654 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897  1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904 -1.25388067]
 [-0.6377515   0.9071052  -1.4286807  -0.14006872 -0.8617549 ]
 [-0.25561937 -2.79858911 -1.7715331  -0.69987723  0.92746243]
 [-0.17363568  0.00284592  0.68822271 -0.87953634  0.28362732]
 [-0.80536652 -1.72766949 -0.39089979  0.57380586  0.33858905]
 [-0.01183049  2.39236527  0.41291216  0.97873601  2.23814334]]
