##### 1.Visualization of U,S, and V for Singular Value Decomposition of a square matrix M, where m=n

In [1]:
import numpy as np
from matplotlib import pyplot as plt
plt.rcParams['image.cmap'] = 'RdBu_r'

In [2]:
PRECISION = 3

def svd(M):
    """Returns the Singular Value Decomposition of M (via numpy), with all components returned in 
    matrix format
    """
    U, s, Vt = np.linalg.svd(M)
    
    # Put the vector singular values into a padded matrix
    S = np.zeros(M.shape)
    np.fill_diagonal(S, s)
    
    # Rounding for display
    return np.round(U, PRECISION), np.round(S, PRECISION), np.round(Vt.T, PRECISION)

In [ ]:
def visualize_svd(m, n, fig_height=5):
    """Show the Singular Value Decomposition of a random matrix of size `m x `n
    Parameters
    ----------
    m : int, The number of rows in the random matrix
    n : int, The number of columns
    fig_height : float, Fiddle parameter to make figures render better(because I'm lazy and
                        don't want to work out the scaling arithmetic).
    """
    np.random.seed(123)
    
    # Generate a random matrix
    M = np.random.randn(m, n)
    
    # Run SVD
    U, S, V = svd(M)
    
    # Visulaization
    fig, axs = plt.subplots(1, 7, figsize=(12, fig_height))
    
    plt.sca(axs[0])  # Set the current Axes to axs[0] and the current Figure to the parent of axs[0].
    plt.imshow(M)
    plt.title(f"$M \\in \\mathbb^{m} \\times {n}$", fontsize=14)
    
    plt.sca(axs[1])
    plt.text(.25, .25, '=', fontsize=48)

In [16]:
np.random.seed(123)

M = np.random.randn(5, 4)
print(M)
print()

U, s, Vt = np.linalg.svd(M)
print(f"U shape : {U.shape},  s shape : {s.shape},  Vt shape : {Vt.shape}")
print()

print(s)
print()

S = np.zeros(M.shape)
np.fill_diagonal(S, s)
print(S)

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]]

U shape : (5, 5),  s shape : (4,),  Vt shape : (4, 4)

[3.42555004 3.17379117 2.5402854  1.42968271]

[[3.42555004 0.         0.         0.        ]
 [0.         3.17379117 0.         0.        ]
 [0.         0.         2.5402854  0.        ]
 [0.         0.         0.         1.42968271]
 [0.         0.         0.         0.        ]]
