In [1]:
import numpy as np

##### A 3*3 matrix

In [16]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0]])

print(A)
print()

A_inv = np.linalg.inv(A)
print(A_inv)
print()

AA_inv = np.round(np.matmul(A, A_inv))
print(AA_inv)

[[1 2 3]
 [0 1 4]
 [5 6 0]]

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


##### A 5*3 matrix

In [17]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0],[1, 0, 1], [2, 5, 3]])
print(A)

[[1 2 3]
 [0 1 4]
 [5 6 0]
 [1 0 1]
 [2 5 3]]


In [18]:
ATA = np.matmul(A.T, A)
ATA_inv = np.linalg.inv(ATA)
A_left_inv = np.matmul(ATA_inv, A.T)
print(A_left_inv)

[[ 0.08478039  0.06945863  0.22574055  0.42390194 -0.31869254]
 [-0.06435138 -0.08886619 -0.03881512 -0.32175689  0.29009193]
 [ 0.10745659  0.15791624 -0.03677222  0.13728294 -0.03043922]]


In [19]:
np.round(np.matmul(A, A_left_inv))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.,  0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0., -0.,  1.]])

##### A 3*5 matrix

In [20]:
A = np.array([[1, 0, 5, 1, 2],[2, 1, 6, 0, 5],[3, 4, 0, 1, 3]])
print(A)

[[1 0 5 1 2]
 [2 1 6 0 5]
 [3 4 0 1 3]]


In [21]:
AAT = np.matmul(A, A.T)
AAT_inv = np.linalg.inv(AAT)
A_right_inv = np.matmul(A.T, AAT_inv)
print(A_right_inv)

[[ 0.08478039 -0.06435138  0.10745659]
 [ 0.06945863 -0.08886619  0.15791624]
 [ 0.22574055 -0.03881512 -0.03677222]
 [ 0.42390194 -0.32175689  0.13728294]
 [-0.31869254  0.29009193 -0.03043922]]


In [22]:
np.round(np.matmul(A, A_right_inv))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

##### Inverse 구해보기 : Z1 = np.matmul(w1, X) + b1

In [ ]:
# X.shape : (5, 8)
# Z.shape : (3, 8)

In [30]:
# Input matrix (5, 8)
X = np.array([[1, 0, 5, 1, 2, 9, 2, 5],[2, 1, 6, 0, 5, 5, 1, 4],[3, 4, 0, 1, 3, 2, 9, 1],[2, 9, 0, 1, 5, 3, 2, 5],[7, 7, 2, 8, 5, 4, 3, 7]])
print(X)
print()

n_h, n_x = 3, X.shape[0]

np.random.seed(2023)
w1 = np.random.randn(n_h, n_x)
print(np.round(w1, 4))
print()

b1 = np.random.randn(n_h, 1)
print(b1)
print()

Z = np.matmul(w1, X) + b1
print(np.round(Z, 4))

[[1 0 5 1 2 9 2 5]
 [2 1 6 0 5 5 1 4]
 [3 4 0 1 3 2 9 1]
 [2 9 0 1 5 3 2 5]
 [7 7 2 8 5 4 3 7]]

[[ 0.7117 -0.3245 -1.0019  0.2363 -0.1022]
 [-1.1413  2.6544  1.4406  0.0989 -3.1215]
 [-1.0765 -0.3257 -1.0355 -0.4263 -1.0294]]

[[-0.5217742 ]
 [-0.42275757]
 [-0.09924417]]

[[ -3.7073  -3.4426   0.8854  -1.393   -3.056    2.5572  -8.2737   1.2029]
 [-13.5863 -12.9665   3.5542 -24.9968  -0.2246  -6.7306   3.7477 -15.4272]
 [-12.9918 -15.6093  -9.4947 -10.8725 -14.2656 -18.8838 -15.8382 -17.1572]]


In [31]:
WWT = np.matmul(w1, w1.T)
WWT_inv = np.linalg.inv(WWT)
W_right_inv = np.matmul(w1.T, WWT_inv)

print(W_right_inv)

[[ 0.63544257  0.07232262 -0.40985194]
 [ 0.13444866  0.1705723  -0.20273896]
 [-0.48856833  0.02997828 -0.25440552]
 [ 0.28679377  0.06315043 -0.18575986]
 [-0.33439154 -0.18591522 -0.14584528]]


In [34]:
# Z = np.matmul(w1, X) + b  -->  Z-b = np.matmul(w1, X)  -->  X = np.matmul(W_right_inv, Z-b1)

X_proxy = np.matmul(W_right_inv, Z-b1)
print(X_proxy.shape)
print()
print(np.round(X_proxy))

(5, 8)

[[ 2.  4.  5.  2.  4.  9.  2.  7.]
 [-0.  1.  3. -2.  3.  3.  3.  1.]
 [ 4.  5.  2.  2.  5.  3.  8.  3.]
 [ 1.  1.  2.  0.  2.  4.  1.  3.]
 [ 5.  6.  0.  6.  3.  3.  4.  5.]]


In [35]:
print(X)

[[1 0 5 1 2 9 2 5]
 [2 1 6 0 5 5 1 4]
 [3 4 0 1 3 2 9 1]
 [2 9 0 1 5 3 2 5]
 [7 7 2 8 5 4 3 7]]
