In [1]:
import numpy as np

##### A 3*3 matrix

In [16]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0]])

print(A)
print()

A_inv = np.linalg.inv(A)
print(A_inv)
print()

AA_inv = np.round(np.matmul(A, A_inv))
print(AA_inv)

[[1 2 3]
 [0 1 4]
 [5 6 0]]

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


##### A 5*3 matrix

In [17]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0],[1, 0, 1], [2, 5, 3]])
print(A)

[[1 2 3]
 [0 1 4]
 [5 6 0]
 [1 0 1]
 [2 5 3]]


In [18]:
ATA = np.matmul(A.T, A)
ATA_inv = np.linalg.inv(ATA)
A_left_inv = np.matmul(ATA_inv, A.T)
print(A_left_inv)

[[ 0.08478039  0.06945863  0.22574055  0.42390194 -0.31869254]
 [-0.06435138 -0.08886619 -0.03881512 -0.32175689  0.29009193]
 [ 0.10745659  0.15791624 -0.03677222  0.13728294 -0.03043922]]


In [19]:
np.round(np.matmul(A, A_left_inv))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.,  0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0., -0.,  1.]])

##### A 3*5 matrix

In [20]:
A = np.array([[1, 0, 5, 1, 2],[2, 1, 6, 0, 5],[3, 4, 0, 1, 3]])
print(A)

[[1 0 5 1 2]
 [2 1 6 0 5]
 [3 4 0 1 3]]


In [21]:
AAT = np.matmul(A, A.T)
AAT_inv = np.linalg.inv(AAT)
A_right_inv = np.matmul(A.T, AAT_inv)
print(A_right_inv)

[[ 0.08478039 -0.06435138  0.10745659]
 [ 0.06945863 -0.08886619  0.15791624]
 [ 0.22574055 -0.03881512 -0.03677222]
 [ 0.42390194 -0.32175689  0.13728294]
 [-0.31869254  0.29009193 -0.03043922]]


In [22]:
np.round(np.matmul(A, A_right_inv))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

##### Inverse 구해보기 : Z1 = np.matmul(w1, X) + b1

In [ ]:
# X.shape : (5, 8)
# Z.shape : (3, 8)

In [26]:
# Input matrix (5, 8)
X = np.array([[1, 0, 5, 1, 2, 9, 2, 5],[2, 1, 6, 0, 5, 5, 1, 4],[3, 4, 0, 1, 3, 2, 9, 1],[2, 9, 0, 1, 5, 3, 2, 5],[7, 7, 2, 8, 5, 4, 3, 7]])
print(X)
print()

n_h, n_x = 3, X.shape[0]

np.random.seed(2023)
w1 = np.random.randn(n_h, n_x)
print(np.round(w1, 4))

[[1 0 5 1 2 9 2 5]
 [2 1 6 0 5 5 1 4]
 [3 4 0 1 3 2 9 1]
 [2 9 0 1 5 3 2 5]
 [7 7 2 8 5 4 3 7]]

[[ 0.7117 -0.3245 -1.0019  0.2363 -0.1022]
 [-1.1413  2.6544  1.4406  0.0989 -3.1215]
 [-1.0765 -0.3257 -1.0355 -0.4263 -1.0294]]
