In [1]:
import numpy as np
from numpy import linalg

##### A square matrix

In [8]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0]])

print(A)
print()

A_inv = linalg.inv(A)
print(A_inv)
print()

AA_inv = np.round(np.matmul(A, A_inv))
print(AA_inv)

(3, 3)
[[1 2 3]
 [0 1 4]
 [5 6 0]]

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [5]:
A_inv = linalg.inv(A)
print(A_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [7]:
np.round(np.matmul(A, A_inv))

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])