In [1]:
import numpy as np

##### A 3*3 matrix

In [16]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0]])

print(A)
print()

A_inv = np.linalg.inv(A)
print(A_inv)
print()

AA_inv = np.round(np.matmul(A, A_inv))
print(AA_inv)

[[1 2 3]
 [0 1 4]
 [5 6 0]]

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


##### A 5*3 matrix

In [17]:
A = np.array([[1, 2, 3],[0, 1, 4],[5, 6, 0],[1, 0, 1], [2, 5, 3]])
print(A)

[[1 2 3]
 [0 1 4]
 [5 6 0]
 [1 0 1]
 [2 5 3]]


In [18]:
ATA = np.matmul(A.T, A)
ATA_inv = np.linalg.inv(ATA)
A_left_inv = np.matmul(ATA_inv, A.T)
print(A_left_inv)

[[ 0.08478039  0.06945863  0.22574055  0.42390194 -0.31869254]
 [-0.06435138 -0.08886619 -0.03881512 -0.32175689  0.29009193]
 [ 0.10745659  0.15791624 -0.03677222  0.13728294 -0.03043922]]


In [19]:
np.round(np.matmul(A, A_left_inv))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.,  0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0.,  0.,  0., -0.,  1.]])

##### A 3*5 matrix

In [20]:
A = np.array([[1, 0, 5, 1, 2],[2, 1, 6, 0, 5],[3, 4, 0, 1, 3]])
print(A)

[[1 0 5 1 2]
 [2 1 6 0 5]
 [3 4 0 1 3]]


In [21]:
AAT = np.matmul(A, A.T)
AAT_inv = np.linalg.inv(AAT)
A_right_inv = np.matmul(A.T, AAT_inv)
print(A_right_inv)

[[ 0.08478039 -0.06435138  0.10745659]
 [ 0.06945863 -0.08886619  0.15791624]
 [ 0.22574055 -0.03881512 -0.03677222]
 [ 0.42390194 -0.32175689  0.13728294]
 [-0.31869254  0.29009193 -0.03043922]]


In [22]:
np.round(np.matmul(A, A_right_inv))

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])