In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [2]:
# Construct a list that contains the number of neurons of each layer in your network.
structure = input("Enter the number of neurons of each layer in your network").split(' ')
structure = [int(x) for x in structure]
print(structure)    

[4, 3, 3]


In [3]:
# Construct a list that contains all the bias vectors of your network(_n means it has all vectors)
np.random.seed(123)
B_n = [np.random.randn(l, 1) for l in structure[1:]]
print("bias vector of each layer\n")
for B in B_n:
    print(B)
    print()

bias vector of each layer

[[-1.0856306 ]
 [ 0.99734545]
 [ 0.2829785 ]]

[[-1.50629471]
 [-0.57860025]
 [ 1.65143654]]



In [4]:
# Construct a list that contains all the weight matrices of your network(_n means it has all matrices)
np.random.seed(123)
W_n = [np.random.randn(l, next_l) for l, next_l in zip(structure[:-1], structure[1:])]
print("weight matrix of each layer\n")
for W in W_n:
    print(W)
    print()

weight matrix of each layer

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]
 [-0.8667404  -0.67888615 -0.09470897]]

[[ 1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609]
 [ 1.0040539   0.3861864   0.73736858]]



In [5]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
data = load_iris()['data']
target = load_iris()['target']

print(type(data), type(target))
print(data.shape, target.shape)
print(len(data), len(target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(150, 4) (150,)
150 150


In [9]:
# Just pick up 5 indexes out of dataset randomly
ind = np.arange(len(data))
np.random.shuffle(ind)
indexes = ind.tolist()

data = data[indexes]
target = target[indexes]

print(data[-5:])
print()
print(target[-5:])

[[6.3 3.3 6.  2.5]
 [4.8 3.  1.4 0.1]
 [6.  3.  4.8 1.8]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.5 0.1]]

[2 0 2 1 0]


In [12]:
kind_labels, count_labels = np.unique(target, return_counts=True)
num_labels = len(kind_labels)
print(f"label의 종류 : {kind_labels},  label종류의 갯수 : {num_labels}")

label의 종류 : [0 1 2],  label종류의 갯수 : 3


In [13]:
X = data
print(X[-5:])
print()

Y = np.zeros((len(X), num_labels))
for i in range(len(Y)):
    for j in range(len(Y[i])):
        Y[i, target[i]] = 1
print(Y[-5:])

[[6.3 3.3 6.  2.5]
 [4.8 3.  1.4 0.1]
 [6.  3.  4.8 1.8]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.5 0.1]]

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [14]:
# B_n is a list of 3 np.ndarrays with (2, 1),(2, 1),(3, 1)
# W_n is a list of 3 np.ndarrays with (4, 2),(2, 2),(2, 3)

# X is a np.ndarray with shape (150,4)
# Y is a np.ndarray with shape (150,3)

# Z_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)
# A_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)

# e_Je_B_ns a list of 3 np.ndarrays with (2,1), (2,1), (3,1)
# e_Je_W_ns a list of 3 np.ndarrays with (4,2), (2,2), (2,3)

In [15]:
# Provide sigmoid and sigmoid_derivative function
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

In [16]:
# Set the output layer to H and let L begin from the first hidden layer(not from the input layer)
H = len(structure) - 2
learning_rate = 0.10
epochs = 20

total_epoch_error = []

1

In [42]:
# Provide softmax and softmax_derivative function
def softmax(x):
    exp_sum = np.sum([np.exp(i) for i in x])
    softmax_x = np.array([np.exp(i)/exp_sum for i in x])
    return softmax_x

In [59]:
# Calculate the Loss
def calculate_loss(actual, expected):
    loss = - np.dot(actual.T, expected)
    return loss

In [52]:
a = np.array([2,5,1]).reshape(-1,1)
y = np.array([0,1,0]).reshape(-1,1)

exp_sum = np.sum([np.exp(i)[0] for i in a])
print(exp_sum)
softmax_x = [np.exp(i[0])/exp_sum for i in a]
print(softmax_x)

158.5204970299663
[0.04661262257797389, 0.9362395518765058, 0.01714782554552039]


In [62]:
 - np.dot(np.array([0,1,0]).T, np.array([0.04661262257797389, 0.9362395518765058, 0.01714782554552039]))

-0.9362395518765058

In [53]:
[np.exp(i)[0] for i in a]

[7.38905609893065, 148.4131591025766, 2.718281828459045]

In [57]:
2.718281828459045 /158.5204970299663

0.01714782554552039

In [63]:
softmax(a)

array([[0.04661262],
       [0.93623955],
       [0.01714783]])

In [66]:
calculate_loss(softmax(a), y)[0][0]

-0.9362395518765058