In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [18]:
structure = input("Enter the number of neurons of each layer in your network").split(" ")
structure = [int(x) for x in structure]
print(structure)

[4, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3]


In [19]:
data = load_iris()["data"]
target = load_iris()["target"]

In [4]:
data = data[[2, 57, 105, 15, 75, 125]]
target = target[[2, 57, 105, 15, 75, 125]]

In [20]:
for x, y in zip(data, target):
    print(x, y)

[5.1 3.5 1.4 0.2] 0
[4.9 3.  1.4 0.2] 0
[4.7 3.2 1.3 0.2] 0
[4.6 3.1 1.5 0.2] 0
[5.  3.6 1.4 0.2] 0
[5.4 3.9 1.7 0.4] 0
[4.6 3.4 1.4 0.3] 0
[5.  3.4 1.5 0.2] 0
[4.4 2.9 1.4 0.2] 0
[4.9 3.1 1.5 0.1] 0
[5.4 3.7 1.5 0.2] 0
[4.8 3.4 1.6 0.2] 0
[4.8 3.  1.4 0.1] 0
[4.3 3.  1.1 0.1] 0
[5.8 4.  1.2 0.2] 0
[5.7 4.4 1.5 0.4] 0
[5.4 3.9 1.3 0.4] 0
[5.1 3.5 1.4 0.3] 0
[5.7 3.8 1.7 0.3] 0
[5.1 3.8 1.5 0.3] 0
[5.4 3.4 1.7 0.2] 0
[5.1 3.7 1.5 0.4] 0
[4.6 3.6 1.  0.2] 0
[5.1 3.3 1.7 0.5] 0
[4.8 3.4 1.9 0.2] 0
[5.  3.  1.6 0.2] 0
[5.  3.4 1.6 0.4] 0
[5.2 3.5 1.5 0.2] 0
[5.2 3.4 1.4 0.2] 0
[4.7 3.2 1.6 0.2] 0
[4.8 3.1 1.6 0.2] 0
[5.4 3.4 1.5 0.4] 0
[5.2 4.1 1.5 0.1] 0
[5.5 4.2 1.4 0.2] 0
[4.9 3.1 1.5 0.2] 0
[5.  3.2 1.2 0.2] 0
[5.5 3.5 1.3 0.2] 0
[4.9 3.6 1.4 0.1] 0
[4.4 3.  1.3 0.2] 0
[5.1 3.4 1.5 0.2] 0
[5.  3.5 1.3 0.3] 0
[4.5 2.3 1.3 0.3] 0
[4.4 3.2 1.3 0.2] 0
[5.  3.5 1.6 0.6] 0
[5.1 3.8 1.9 0.4] 0
[4.8 3.  1.4 0.3] 0
[5.1 3.8 1.6 0.2] 0
[4.6 3.2 1.4 0.2] 0
[5.3 3.7 1.5 0.2] 0
[5.  3.3 1.4 0.2] 0


In [21]:
one_hot_labels = np.zeros((len(data), 3))
for i in range(len(one_hot_labels)):
    for j in range(len(one_hot_labels[i])):
        one_hot_labels[i, target[i]] = 1
print(one_hot_labels)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [22]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

def softmax(x):
    exponential_sum = np.sum([np.exp(i) for i in x])
    exponential_x = np.array([np.exp(i) / exponential_sum for i in x])
    return exponential_x

def calculate_loss(actual, expected):
    loss = - np.sum(actual.reshape(-1) * expected)
    return loss

In [8]:
actual = np.array([[0.08], [0.24], [0.72]])
expected = np.array([0, 0, 1])
calculate_loss(actual, expected)

-0.72

In [23]:
H = len(structure) - 2
learning_rate = 15
epochs = 50
all_epoch_errors = []

for epoch in range(epochs):
    each_epoch_errors = []
    sum_losses = 0

    w_n = [np.random.randn(l, next_l) for l,next_l in zip(structure[:-1], structure[1:])] # (4,2), (2,3)
    b_n = [np.random.randn(l, 1) for l in structure[1:]]  # (2,1), (3,1)   

    
    for k, (x, y) in enumerate(zip(data, one_hot_labels)):
        z_n, a_n = [], []
        
        # np.random.seed(2023)
        # w_n = [np.random.randn(l, next_l) for l,next_l in zip(structure[:-1], structure[1:])] # (4,2), (2,3)
        # b_n = [np.random.randn(l, 1) for l in structure[1:]]  # (2,1), (3,1)
        
        for i, (b, w) in enumerate(zip(b_n, w_n)):
            if i == 0:
                z = np.dot(w.T, x).reshape(-1,1) + np.array(b)
                a = sigmoid(z)                
                
            elif (i > 0) and (i < H):
                z = np.dot(w.T, a)
                a = sigmoid(z)
            else:
                z = np.dot(w.T, a)
                a = softmax(z)
            
            """    
            print(z)
            print(a)
            print()
            """                
            z_n.append(z)
            a_n.append(a)
        
        #print(f"{epoch}-{k}th softmax loss : {loss}")
        
        # BackPropagate
        # np.random.seed(2023)
        e_je_w_ns = [np.zeros(w.shape) for w in w_n]
        e_je_b_ns = [np.zeros(b.shape) for b in b_n]
                
        datapoint_errors = []
        
        for L in range(H, -1, -1):
            if L != H:
                delta = sigmoid_derivative(z_n[L]) * np.dot(w_n[L+1], delta)
            else:
                #print(y.reshape(-1,1).shape)
                delta = a_n[L] - y.reshape(-1, 1)   # (3,1)                
            e_je_b_ns[L] = delta
            
            if L != 0:
                e_je_w_ns[L] = np.dot(a_n[L-1], delta.T)                
                #print(f"delta.T shape : {delta.T.shape}")
                #print(f"a_n[L] shape : {a_n[L].shape}")                
            else:
                #print(f"x : {x.reshape(-1,1).shape}")
                #print(f"delta : {delta.T.shape}")
                e_je_w_ns[L] = np.dot(x.reshape(-1,1), delta.T)   # (4,1), (1,2), (4,2)          
        """      
        print(f"{epoch}epoch {k}th data e_je_w_ns :\n {e_je_w_ns}")
        print(f"{epoch}epoch {k}th data e_je_b_ns :\n {e_je_b_ns}")
        print()
        """
        for i, (wn, ejew, bn, ejeb) in enumerate(zip(w_n, e_je_w_ns, b_n, e_je_b_ns)):
            w_n[i] -= learning_rate/len(data) * ejew
            b_n[i] -= learning_rate/len(data) * ejeb
        
        loss = calculate_loss(a_n[-1], y)
        sum_losses += loss
    print(f"{epoch}th loss : {sum_losses}")        

0th loss : -121.07933305963672
1th loss : -122.91616000918651
2th loss : -101.56251364647768
3th loss : -116.85458118084759
4th loss : -116.22651307899231
5th loss : -112.07319060953385
6th loss : -96.81227191438118
7th loss : -120.62896240276164
8th loss : -121.93032403066277
9th loss : -121.92787290484411
10th loss : -110.81918355133072
11th loss : -120.79432894263006
12th loss : -122.0808611263011
13th loss : -107.76229463268129
14th loss : -127.86288307142127
15th loss : -110.5838271396887
16th loss : -111.66085961554562
17th loss : -114.21720092374554
18th loss : -111.71912840239845
19th loss : -115.41915501897888
20th loss : -118.26373803975257
21th loss : -118.2738040018823
22th loss : -116.71159840761422
23th loss : -116.95067575172618
24th loss : -102.66474975634394
25th loss : -127.98054347199766
26th loss : -122.60026916979194
27th loss : -113.31255587234405
28th loss : -123.66518642052851
29th loss : -99.77037127440038
30th loss : -100.22010638942898
31th loss : -111.154912

In [27]:
z_n

[array([[ 6.27374581],
        [-6.78636791]]),
 array([[ 0.09834887],
        [-3.11682648],
        [-1.07497685]])]

In [28]:
a_n

[array([[0.99811839],
        [0.00112779]]),
 array([[0.74102356],
        [0.02975083],
        [0.22922561]])]

In [29]:
a0, a1, a2 = np.exp(0.09834887), np.exp(-3.11682648), np.exp(-1.07497685)
a = a0 + a1 + a2
print(a0, a1, a2)
print(a0/a, a1/a, a2/a)

1.1033476428641078 0.04429752467070435 0.34130565643548416
0.7410235617601022 0.029750831227981552 0.22922560701191635


In [30]:
softmax(z_n[1])

array([[0.74102356],
       [0.02975083],
       [0.22922561]])