In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [2]:
structure = input("Enter the number of neurons of each layer in your network").split(" ")
structure = [int(x) for x in structure]
print(structure)

[4, 2, 3]


In [30]:
data = load_iris()["data"]
target = load_iris()["target"]

In [31]:
data = data[[2, 57, 105]]
target = target[[2, 57, 105]]

In [32]:
for x, y in zip(data, target):
    print(x, y)

[4.7 3.2 1.3 0.2] 0
[4.9 2.4 3.3 1. ] 1
[7.6 3.  6.6 2.1] 2


In [34]:
one_hot_labels = np.zeros((len(data), 3))
for i in range(len(one_hot_labels)):
    for j in range(len(one_hot_labels[i])):
        one_hot_labels[i, target[i]] = 1
print(one_hot_labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

def softmax(x):
    exponential_sum = np.sum([np.exp(i) for i in x])
    exponential_x = np.array([np.exp(i) / exponential_sum for i in x])
    return exponential_x

def calculate_loss(actual, expected):
    loss = - np.sum(actual.reshape(-1) * expected)
    return loss

In [36]:
actual = np.array([[0.08], [0.24], [0.72]])
expected = np.array([0, 0, 1])
calculate_loss(actual, expected)

-0.72

In [44]:
H = len(structure) - 2
learning_rate = 0.10
epochs = 5
all_epoch_errors = []

for epoch in range(epochs):
    each_epoch_errors = []
    
    w_n = [np.random.randn(l, next_l) for l,next_l in zip(structure[:-1], structure[1:])] # (4,2), (2,3)
    b_n = [np.random.randn(l, 1) for l in structure[1:]]  # (2,1), (3,1)
    
    for x, y in zip(data, one_hot_labels):
        z_n, a_n = [], []
        
        for i, (b, w) in enumerate(zip(b_n, w_n)):
            if i == 0:
                z = np.dot(w.T, x).reshape(-1,1) + np.array(b)
                a = sigmoid(z)                
                
            elif (i > 0) and (i < H):
                z = np.dot(w.T, a)
                a = sigmoid(z)
            else:
                z = np.dot(w.T, a)
                a = softmax(z)
                
            print(z)
            print(a)
            print()
                
            z_n.append(z)
            a_n.append(a)

[[ 7.35041771]
 [-6.57518822]]
[[0.99935809]
 [0.0013926 ]]

[[-0.79373435]
 [ 0.01638831]
 [-1.32673294]]
[[0.2607544]
 [0.5862238]
 [0.1530218]]

[[ 7.11085781]
 [-8.56218539]]
[[9.99184471e-01]
 [1.91164438e-04]]

[[-0.79376265]
 [ 0.01565836]
 [-1.32558037]]
[[0.26081449]
 [0.58594761]
 [0.15323791]]

[[ 10.56357158]
 [-13.78737014]]
[[9.99974160e-01]
 [1.02853904e-06]]

[[-0.79441631]
 [ 0.01555555]
 [-1.32648195]]
[[0.26074021]
 [0.5861035 ]
 [0.15315629]]

[[-6.14762235]
 [ 2.32828019]]
[[0.002134  ]
 [0.91119227]]

[[ 0.23033119]
 [-1.08996592]
 [ 1.07771299]]
[[0.27773263]
 [0.07417015]
 [0.64809721]]

[[-11.32130652]
 [  0.91854789]]
[[1.21119423e-05]
 [7.14746136e-01]]

[[ 0.17948986]
 [-0.85479436]
 [ 0.84783006]]
[[0.30243669]
 [0.10751042]
 [0.59005289]]

[[-21.21213435]
 [  0.24005462]]
[[6.13319967e-10]
 [5.59727109e-01]]

[[ 0.14055412]
 [-0.66939967]
 [ 0.66396095]]
[[0.31921892]
 [0.14201367]
 [0.53876741]]

[[3.66447232]
 [4.41523365]]
[[0.97502219]
 [0.98805273]]



In [45]:
z_n

[array([[-5.56084448],
        [-1.09959882]]),
 array([[-0.05061309],
        [-0.03384948],
        [-0.47838968]])]

In [46]:
a_n

[array([[0.0038308 ],
        [0.24981507]]),
 array([[0.37469154],
        [0.38102567],
        [0.24428279]])]