In [1]:
import numpy as np

In [50]:
# Construct a list that contains the number of neurons of each layer in your network.
structure = input("Enter the number of neurons of each layer in your network").split(' ')
structure = [int(x) for x in structure]
print(structure)    

[2, 3, 2]


In [51]:
# Construct a list that contains all the bias vectors of your network(_n means it has all vectors)
B_n = [np.random.randn(l, 1) for l in structure[1:]]
print("bias vector of each layer\n")
for B in B_n:
    print(B)
    print()

# Construct a list that contains all the weight matrices of your network(_n means it has all matrices)
W_n = [np.random.randn(l, next_l) for l, next_l in zip(structure[:-1], structure[1:])]
print("weight matrix of each layer\n")
for W in W_n:
    print(W)
    print()

bias vector of each layer

[[-0.79470329]
 [-0.79819553]
 [ 0.2514908 ]]

[[1.61843934]
 [1.37334835]]

weight matrix of each layer

[[ 0.54686406  0.16518578 -0.87594857]
 [ 0.5951226   0.49727308  0.43360012]]

[[ 0.76307621 -0.94700626]
 [ 0.15605292 -0.03794118]
 [ 0.15664071 -0.79214579]]



##### Forward Pass

In [60]:
B_n

[array([[-0.79470329],
        [-0.79819553],
        [ 0.2514908 ]]),
 array([[1.61843934],
        [1.37334835]])]

In [52]:
# Provide sigmoid and sigmoid_derivative function
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

In [53]:
x = np.array([2, 5])

In [75]:
np.array(B_n[0]).reshape(-1)

array([-0.79470329, -0.79819553,  0.2514908 ])

In [76]:
np.dot(W_n[0].T, x) + np.array(B_n[0]).reshape(-1)

array([3.27463785, 2.01854144, 0.66759429])

In [77]:
# Create two lists that contain pre and post activation vector of each layer, respectively
Z_n, A_n = [], []

# Forward pass layer by layer from L=0(First hidden layer) thru L=H(Output layer)
for i, (b, W) in enumerate(zip(B_n, W_n)):
    if i == 0:
        z = np.dot(np.array(W).T, x) + np.array(b).reshape(-1)
    else:
        z = np.dot(np.array(W).T, a) + np.array(b).reshape(-1)
    a = sigmoid(z)

    Z_n.append(z)
    A_n.append(a)

In [78]:
for z, a in zip(Z_n, A_n):
    print(np.round(z, 4))
    print(np.round(a, 4))
    print()

[3.2746 2.0185 0.6676]
[0.9635 0.8827 0.661 ]

[ 2.595  -0.0962]
[0.9305 0.476 ]

