In [6]:
import numpy as np
from sklearn.datasets import load_iris

In [36]:
# Construct a list that contains the number of neurons of each layer in your network.
structure = input("Enter the number of neurons of each layer in your network").split(' ')
structure = [int(x) for x in structure]
print(structure)    

[4, 3, 3]


In [37]:
# Construct a list that contains all the bias vectors of your network(_n means it has all vectors)
B_n = [np.random.randn(l, 1) for l in structure[1:]]
print("bias vector of each layer\n")
for B in B_n:
    print(B)
    print()

# Construct a list that contains all the weight matrices of your network(_n means it has all matrices)
W_n = [np.random.randn(l, next_l) for l, next_l in zip(structure[:-1], structure[1:])]
print("weight matrix of each layer\n")
for W in W_n:
    print(W)
    print()

bias vector of each layer

[[-0.07351368]
 [ 1.81403277]
 [-0.44199761]]

[[ 1.38951142]
 [-1.07746533]
 [ 0.23848917]]

weight matrix of each layer

[[ 1.67960037 -1.30580313 -1.13889525]
 [-0.78464639  0.7953204   1.64950807]
 [-0.91948541  2.02837484  0.23634688]
 [-0.46335828 -1.73197305 -0.61783601]]

[[ 1.7104376  -0.05634082 -1.06029955]
 [-1.82207837 -1.21117645  1.48492015]
 [ 0.74102732  0.71157801  0.29822755]]



##### Load training and test datasets

In [38]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [39]:
data = load_iris()['data']
target = load_iris()['target']

print(type(data), type(target))
print(data.shape, target.shape)
print(len(data), len(target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(150, 4) (150,)
150 150


In [40]:
indexes = [0, 52, 108, 49, 142, 88]

data = data[indexes]
target = target[indexes]

print(data)
print(target)

[[5.1 3.5 1.4 0.2]
 [6.9 3.1 4.9 1.5]
 [6.7 2.5 5.8 1.8]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 3.  4.1 1.3]]
[0 1 2 0 2 1]


In [41]:
# Randomly shuffle the data
np.random.seed(123)
np.random.shuffle(data)

np.random.seed(123)
np.random.shuffle(target)

print(data)
print(target)   #2

[[6.9 3.1 4.9 1.5]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.1 3.5 1.4 0.2]
 [6.7 2.5 5.8 1.8]
 [5.6 3.  4.1 1.3]]
[1 0 2 0 2 1]


##### Forward Pass

In [42]:
# Provide sigmoid and sigmoid_derivative function
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

In [43]:
X, y = data[0], target[0]
print(X)
print(y)

[6.9 3.1 4.9 1.5]
1


In [44]:
np.array(B_n[0]).reshape(-1)

array([-0.07351368,  1.81403277, -0.44199761])

In [45]:
np.dot(W_n[0].T, X) + np.array(B_n[0]).reshape(-1)

array([ 3.88280918,  2.61056159, -2.95555412])

In [46]:
# Create two lists that contain pre and post activation vector of each layer, respectively
Z_n, A_n = [], []

# Forward pass layer by layer from L=0(First hidden layer) thru L=H(Output layer)
for i, (b, W) in enumerate(zip(B_n, W_n)):
    if i == 0:
        z = np.dot(np.array(W).T, X) + np.array(b).reshape(-1)
    else:
        z = np.dot(np.array(W).T, a) + np.array(b).reshape(-1)
    a = sigmoid(z)

    Z_n.append(z)
    A_n.append(a)

In [78]:
for z, a in zip(Z_n, A_n):
    print(np.round(z, 4))
    print(np.round(a, 4))
    print()

[3.2746 2.0185 0.6676]
[0.9635 0.8827 0.661 ]

[ 2.595  -0.0962]
[0.9305 0.476 ]



In [83]:
q = np.array([[0.54686406, 0.16518578, -0.87594857], 
              [ 0.5951226, 0.49727308,  0.43360012]])
r = np.array([-0.79470329, -0.79819553, 0.2514908])
y = np.dot(q.T, x) + r
u = sigmoid(y)

print(y)
print(u)

[3.27463783 2.01854143 0.66759426]
[0.96354842 0.88273011 0.66096426]
