In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [2]:
structure = input("Enter the number of neurons of each layer in your network").split(" ")
structure = [int(x) for x in structure]
print(structure)

[4, 2, 3]


In [30]:
data = load_iris()["data"]
target = load_iris()["target"]

In [31]:
data = data[[2, 57, 105]]
target = target[[2, 57, 105]]

In [32]:
for x, y in zip(data, target):
    print(x, y)

[4.7 3.2 1.3 0.2] 0
[4.9 2.4 3.3 1. ] 1
[7.6 3.  6.6 2.1] 2


In [34]:
one_hot_labels = np.zeros((len(data), 3))
for i in range(len(one_hot_labels)):
    for j in range(len(one_hot_labels[i])):
        one_hot_labels[i, target[i]] = 1
print(one_hot_labels)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

def softmax(x):
    exponential_sum = np.sum([np.exp(i) for i in x])
    exponential_x = np.array([np.exp(i) / exponential_sum for i in x])
    return exponential_x

def calculate_loss(actual, expected):
    loss = - np.sum(actual.reshape(-1) * expected)
    return loss

In [36]:
actual = np.array([[0.08], [0.24], [0.72]])
expected = np.array([0, 0, 1])
calculate_loss(actual, expected)

-0.72

In [49]:
H = len(structure) - 2
learning_rate = 0.10
epochs = 5
all_epoch_errors = []

for epoch in range(epochs):
    each_epoch_errors = []
    
    w_n = [np.random.randn(l, next_l) for l,next_l in zip(structure[:-1], structure[1:])] # (4,2), (2,3)
    b_n = [np.random.randn(l, 1) for l in structure[1:]]  # (2,1), (3,1)
    
    for x, y in zip(data, one_hot_labels):
        z_n, a_n = [], []
        
        for i, (b, w) in enumerate(zip(b_n, w_n)):
            if i == 0:
                z = np.dot(w.T, x).reshape(-1,1) + np.array(b)
                a = sigmoid(z)                
                
            elif (i > 0) and (i < H):
                z = np.dot(w.T, a)
                a = sigmoid(z)
            else:
                z = np.dot(w.T, a)
                a = softmax(z)
                
            print(z)
            print(a)
            print()
            
                
            z_n.append(z)
            a_n.append(a)

[[0.11203205]
 [0.30924871]]
[[0.52797875]
 [0.57670187]]

[[ 0.13169669]
 [-0.00397344]
 [-1.13409562]]
[[0.46400561]
 [0.4051375 ]
 [0.1308569 ]]

[[-2.38433828]
 [ 2.64206845]]
[[0.0843748 ]
 [0.93352045]]

[[ 0.06852678]
 [ 0.03920546]
 [-0.9592742 ]]
[[0.42938777]
 [0.41698034]
 [0.15363189]]

[[-6.84179204]
 [ 5.17656315]]
[[0.00106705]
 [0.99438433]]

[[ 0.05631679]
 [ 0.04702334]
 [-0.92075991]]
[[0.42244725]
 [0.41853944]
 [0.15901331]]

[[ -3.65043972]
 [-12.25680804]]
[[2.53218484e-02]
 [4.75262820e-06]]

[[ 0.01506682]
 [-0.00908493]
 [ 0.01943492]]
[[0.33551246]
 [0.32750632]
 [0.33698122]]

[[ -4.73358737]
 [-13.34137194]]
[[8.71818865e-03]
 [1.60662710e-06]]

[[ 0.0051875 ]
 [-0.0031279 ]
 [ 0.00669135]]
[[0.33408792]
 [0.33132136]
 [0.33459072]]

[[ -8.3264858 ]
 [-21.19760379]]
[[2.41962503e-04]
 [6.22296913e-10]]

[[ 1.44074157e-04]
 [-8.68143818e-05]
 [ 1.85711852e-04]]
[[0.33335436]
 [0.3332774 ]
 [0.33336824]]

[[ 2.9549953 ]
 [-9.21443134]]
[[9.5049905e-01]
 [9.95

In [56]:
z_n

[array([[  4.50262653],
        [-11.27215269]]),
 array([[ 1.13915056],
        [-0.76459434],
        [-1.12095286]])]

In [57]:
a_n

[array([[9.89041561e-01],
        [1.27221573e-05]]),
 array([[0.79786221],
        [0.11888909],
        [0.0832487 ]])]

In [53]:
a0, a1, a2 = np.exp(1.13915056), np.exp(-0.76459434), np.exp(-1.12095286)
a = a0 + a1 + a2
print(a0, a1, a2)
print(a0/a, a1/a, a2/a)

3.1241134908039148 0.4655227366296143 0.32596904373249375
0.7978622140003375 0.11888908722686108 0.08324869877280144


In [58]:
softmax(z_n[1])

array([[0.79786221],
       [0.11888909],
       [0.0832487 ]])