In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [2]:
structure = input("Enter the number of neurons of each layer in your network").split(" ")
structure = [int(x) for x in structure]
print(structure)

[4, 2, 3]


In [3]:
data = load_iris()["data"]
target = load_iris()["target"]

In [7]:
one_hot_labels = np.zeros((len(data), 3))
for i in range(len(one_hot_labels)):
    for j in range(len(one_hot_labels[i])):
        one_hot_labels[i, target[i]] = 1
print(one_hot_labels[[45, 57, 97, 103, 147]])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [16]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

def softmax(x):
    exponential_sum = np.sum([np.exp(i) for i in x])
    exponential_x = np.array([np.exp(i) / exponential_sum for i in x])
    return exponential_x

def calculate_loss(actual, expected):
    loss = - np.sum(actual.reshape(-1) * expected)
    return loss

In [19]:
actual = np.array([[0.08], [0.24], [0.72]])
expected = np.array([0, 0, 1])
calculate_loss(actual, expected)

-0.72