In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
# Construct a list that contains the number of neurons of each layer in your network.
structure = input("Enter the number of neurons of each layer in your network").split(' ')
structure = [int(x) for x in structure]
print(structure)    

[4, 2, 2, 3]


In [3]:
# Construct a list that contains all the bias vectors of your network(_n means it has all vectors)
np.random.seed(123)
B_n = [np.random.randn(l, 1) for l in structure[1:]]
print("bias vector of each layer\n")
for B in B_n:
    print(B)
    print()

bias vector of each layer

[[-1.0856306 ]
 [ 0.99734545]]

[[ 0.2829785 ]
 [-1.50629471]]

[[-0.57860025]
 [ 1.65143654]
 [-2.42667924]]



In [4]:
# Construct a list that contains all the weight matrices of your network(_n means it has all matrices)
np.random.seed(123)
W_n = [np.random.randn(l, next_l) for l, next_l in zip(structure[:-1], structure[1:])]
print("weight matrix of each layer\n")
for W in W_n:
    print(W)
    print()

weight matrix of each layer

[[-1.0856306   0.99734545]
 [ 0.2829785  -1.50629471]
 [-0.57860025  1.65143654]
 [-2.42667924 -0.42891263]]

[[ 1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897]]

[[ 1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609]]



##### Load training and test datasets

In [5]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
data = load_iris()['data']
target = load_iris()['target']

print(type(data), type(target))
print(data.shape, target.shape)
print(len(data), len(target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(150, 4) (150,)
150 150


In [7]:
# Just pick up 5 indexes out of dataset randomly
indexes = [0, 52, 108, 49, 142, 88]

data = data[indexes]
target = target[indexes]

print(data)
print()
print(target)

[[5.1 3.5 1.4 0.2]
 [6.9 3.1 4.9 1.5]
 [6.7 2.5 5.8 1.8]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 3.  4.1 1.3]]

[0 1 2 0 2 1]


In [21]:
type(X), type(Y)

(numpy.ndarray, numpy.ndarray)

In [8]:
X = data
print(X)
print()

Y = np.zeros((6, 3))
for i in range(len(Y)):
    for j in range(len(Y[i])):
        Y[i, target[i]] = 1
print(Y)

[[5.1 3.5 1.4 0.2]
 [6.9 3.1 4.9 1.5]
 [6.7 2.5 5.8 1.8]
 [5.  3.3 1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 3.  4.1 1.3]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [11]:
# B_n is a list of 3 np.ndarrays with (2, 1),(2, 1),(3, 1)
# W_n is a list of 3 np.ndarrays with (4, 2),(2, 2),(2, 3)

# X is a np.ndarray with shape (6,4)
# Y is a np.ndarray with shape (6,3)

# Z_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)
# A_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)

# e_Je_B_ns a list of 3 np.ndarrays with (2,1), (2,1), (3,1)
# e_Je_W_ns a list of 3 np.ndarrays with (4,2), (2,2), (2,3)

B_n의 타입은 <class 'list'>이다.
W_n의 타입은 <class 'list'>이다.
X의 타입은 <class 'numpy.ndarray'>이다.
Y의 타입은 <class 'numpy.ndarray'>이다.


In [12]:
# Provide sigmoid and sigmoid_derivative function
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

In [35]:
# Set the output layer to H and let L begin from the first hidden layer(not from the input layer)
H = len(structure) - 2

for x, y in zip(X, Y):     # x의 shape:(4,),  y의 shape:(3,)
    
    # Forward Propagate
    # Create two lists that contain pre and post activation vector of each layer, respectively
    Z_n, A_n = [], []
    
    for i, (b, W) in enumerate(zip(B_n, W_n)):
        if i == 0:
            z = np.dot(np.array(W).T, x).reshape(-1, 1) + np.array(b)
        else:
            z = np.dot(np.array(W).T, a).reshape(-1, 1) + np.array(b)
        a = sigmoid(z)

        Z_n.append(z)
        A_n.append(a)
    # print(Z_n) 
    # print()  
    
    
    # Backpropagate
    # Initialize a list called e_Je_W_ns that will contain e_Je_W matrices for each layer
    e_Je_W_ns = [np.zeros(W.shape) for W in W_n]    # (4, 2), (2, 2), (2, 3)
    #for x in e_Je_W_ns:
    #    print(x.shape)
    #print()

    # Initialize a list called e_Je_B_ns that will contain e_Je_B vectors for each layer
    e_Je_B_ns = [np.zeros(B.shape) for B in B_n]    # (2, 1), (2, 1), (3, 1)
    
    for L in range(H, -1, -1):
        if L != H:
            delta = sigmoid_derivative(Z_n[L]) * np.dot(W_n[L+1], delta)
        else:
            delta = sigmoid_derivative(Z_n[L]) * (A_n[L] - y.reshape(-1, 1))
            
        e_Je_B_ns[L] = delta
        # print(f"{L} : {delta}")
        
        if L != 0:
            e_Je_W_ns[L] = np.dot(A_n[L-1], delta.T)
        else:
            e_Je_W_ns[L] = np.dot(x.reshape(-1, 1), delta.T)
    
    for x in e_Je_W_ns:
        print(x)
    print()

[[-5.87872410e-04  8.66681145e-03]
 [-4.03441850e-04  5.94781178e-03]
 [-1.61376740e-04  2.37912471e-03]
 [-2.30538200e-05  3.39874959e-04]]
[[-6.21037426e-05  4.24149591e-05]
 [-6.04920568e-02  4.13142269e-02]]
[[-0.05226762  0.04380252  0.00342724]
 [-0.02145442  0.01797973  0.00140679]]

[[ 3.21524798e-07 -4.85530138e-06]
 [ 1.44453170e-07 -2.18136729e-06]
 [ 2.28329204e-07 -3.44796765e-06]
 [ 6.98966952e-08 -1.05550030e-06]]
[[ 3.18149726e-08 -7.29411251e-09]
 [ 4.55500704e-02 -1.04431125e-02]]
[[ 0.04895998 -0.00734256  0.00337597]
 [ 0.02042635 -0.00306335  0.00140847]]

[[ 6.18229747e-08 -4.87869117e-07]
 [ 2.30682742e-08 -1.82040715e-07]
 [ 5.35183960e-08 -4.22334459e-07]
 [ 1.66091574e-08 -1.31069315e-07]]
[[7.49326696e-09 2.98459311e-10]
 [3.56698231e-02 1.42074090e-03]]
[[ 0.04895942  0.04287678 -0.03165622]
 [ 0.02042627  0.01788854 -0.01320724]]

[[-6.06742040e-04  7.06074810e-03]
 [-4.00449746e-04  4.66009375e-03]
 [-1.69887771e-04  1.97700947e-03]
 [-2.42696816e-05  2.82

In [37]:
for x in e_Je_W_ns:
    print(x)
    print()

[[ 2.68546237e-06 -4.26149872e-05]
 [ 1.43864056e-06 -2.28294574e-05]
 [ 1.96614210e-06 -3.12002585e-05]
 [ 6.23410908e-07 -9.89276488e-06]]

[[ 3.27416513e-07 -7.50649946e-08]
 [ 4.55425009e-02 -1.04412803e-02]]

[[ 0.04896634 -0.00734351  0.00337623]
 [ 0.02042727 -0.00306349  0.00140846]]

