In [1]:
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [2]:
# Construct a list that contains the number of neurons of each layer in your network.
structure = input("Enter the number of neurons of each layer in your network").split(' ')
structure = [int(x) for x in structure]
print(structure)    

[4, 3, 3, 3]


In [3]:
# Construct a list that contains all the bias vectors of your network(_n means it has all vectors)
np.random.seed(123)
B_n = [np.random.randn(l, 1) for l in structure[1:]]
print("bias vector of each layer\n")
for B in B_n:
    print(B)
    print()

bias vector of each layer

[[-1.0856306 ]
 [ 0.99734545]
 [ 0.2829785 ]]

[[-1.50629471]
 [-0.57860025]
 [ 1.65143654]]

[[-2.42667924]
 [-0.42891263]
 [ 1.26593626]]



In [4]:
# Construct a list that contains all the weight matrices of your network(_n means it has all matrices)
np.random.seed(123)
W_n = [np.random.randn(l, next_l) for l, next_l in zip(structure[:-1], structure[1:])]
print("weight matrix of each layer\n")
for W in W_n:
    print(W)
    print()

weight matrix of each layer

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]
 [-2.42667924 -0.42891263  1.26593626]
 [-0.8667404  -0.67888615 -0.09470897]]

[[ 1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609]
 [ 1.0040539   0.3861864   0.73736858]]

[[ 1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052 ]
 [-1.4286807  -0.14006872 -0.8617549 ]]



In [5]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
data = load_iris()['data']
target = load_iris()['target']

print(type(data), type(target))
print(data.shape, target.shape)
print(len(data), len(target))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
(150, 4) (150,)
150 150


In [10]:
# Just pick up 5 indexes out of dataset randomly
ind = np.arange(150)
np.random.shuffle(ind)
indexes = ind.tolist()

data = data[indexes]
target = target[indexes]

print(data)
print()
print(target)

[[4.4 3.2 1.3 0.2]
 [7.2 3.  5.8 1.6]
 [5.1 2.5 3.  1.1]
 [5.9 3.  4.2 1.5]
 [4.8 3.4 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.4 5.6 2.4]
 [5.6 3.  4.1 1.3]
 [4.6 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [5.8 4.  1.2 0.2]
 [5.4 3.7 1.5 0.2]
 [5.8 2.7 3.9 1.2]
 [6.1 3.  4.9 1.8]
 [5.4 3.9 1.3 0.4]
 [5.1 3.8 1.9 0.4]
 [7.7 3.8 6.7 2.2]
 [4.3 3.  1.1 0.1]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.7 5.1 1.6]
 [5.7 4.4 1.5 0.4]
 [4.9 2.4 3.3 1. ]
 [6.3 3.3 4.7 1.6]
 [7.7 2.6 6.9 2.3]
 [4.9 3.  1.4 0.2]
 [6.4 3.1 5.5 1.8]
 [4.8 3.  1.4 0.1]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [6.1 2.9 4.7 1.4]
 [6.2 2.9 4.3 1.3]
 [5.  3.5 1.6 0.6]
 [5.7 3.  4.2 1.2]
 [5.7 3.8 1.7 0.3]
 [5.5 2.4 3.7 1. ]
 [4.9 3.6 1.4 0.1]
 [5.3 3.7 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [4.7 3.2 1.3 0.2]
 [6.7 3.1 4.4 1.4]
 [6.6 2.9 4.6 1.3]
 [4.9 2.5 4.5 1.7]
 [5.  3.3 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [6.3 2.5 4.9 1.5]
 [4.8 3.4 1.9 0.2]
 [6.9 3.1 4.9 1.5]
 [5.1 3.8 1.5 0.3]
 [6.4 2.8 5.6 2.2]
 [6.8 3.2 5.9 2.3]
 [6.  2.2 4.

In [11]:
X = data
print(X)
print()

Y = np.zeros((len(X), 3))
for i in range(len(Y)):
    for j in range(len(Y[i])):
        Y[i, target[i]] = 1
print(Y)

[[4.4 3.2 1.3 0.2]
 [7.2 3.  5.8 1.6]
 [5.1 2.5 3.  1.1]
 [5.9 3.  4.2 1.5]
 [4.8 3.4 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.4 5.6 2.4]
 [5.6 3.  4.1 1.3]
 [4.6 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [5.8 4.  1.2 0.2]
 [5.4 3.7 1.5 0.2]
 [5.8 2.7 3.9 1.2]
 [6.1 3.  4.9 1.8]
 [5.4 3.9 1.3 0.4]
 [5.1 3.8 1.9 0.4]
 [7.7 3.8 6.7 2.2]
 [4.3 3.  1.1 0.1]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.7 5.1 1.6]
 [5.7 4.4 1.5 0.4]
 [4.9 2.4 3.3 1. ]
 [6.3 3.3 4.7 1.6]
 [7.7 2.6 6.9 2.3]
 [4.9 3.  1.4 0.2]
 [6.4 3.1 5.5 1.8]
 [4.8 3.  1.4 0.1]
 [5.  3.6 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [6.1 2.9 4.7 1.4]
 [6.2 2.9 4.3 1.3]
 [5.  3.5 1.6 0.6]
 [5.7 3.  4.2 1.2]
 [5.7 3.8 1.7 0.3]
 [5.5 2.4 3.7 1. ]
 [4.9 3.6 1.4 0.1]
 [5.3 3.7 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [4.7 3.2 1.3 0.2]
 [6.7 3.1 4.4 1.4]
 [6.6 2.9 4.6 1.3]
 [4.9 2.5 4.5 1.7]
 [5.  3.3 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [6.3 2.5 4.9 1.5]
 [4.8 3.4 1.9 0.2]
 [6.9 3.1 4.9 1.5]
 [5.1 3.8 1.5 0.3]
 [6.4 2.8 5.6 2.2]
 [6.8 3.2 5.9 2.3]
 [6.  2.2 4.

In [14]:
# B_n is a list of 3 np.ndarrays with (2, 1),(2, 1),(3, 1)
# W_n is a list of 3 np.ndarrays with (4, 2),(2, 2),(2, 3)

# X is a np.ndarray with shape (150,4)
# Y is a np.ndarray with shape (150,3)

# Z_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)
# A_n is a list of 3 np.ndarrays with (2,1),(2,1),(3,1)

# e_Je_B_ns a list of 3 np.ndarrays with (2,1), (2,1), (3,1)
# e_Je_W_ns a list of 3 np.ndarrays with (4,2), (2,2), (2,3)

In [15]:
# Provide sigmoid and sigmoid_derivative function
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1.0 - sigmoid(x))

In [26]:
# Provide softmax and softmax_derivative function
def softmax(i, x):
    total_exp = np.sum([np.exp(k) for k in x])
    return np.exp(x[i]) / total_exp