In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [29]:
reviews = ["Never coming back", "horrible service", "rude waitress", "cold food", "horrible food",
           "awesome", "awesome services!", "rocks", "poor work", "couldn\'t have done better"]

labels = [1 for i in range(5)] + [0 for i in range(5)]   # [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
labels = np.array(labels)

In [8]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(f"encoded_reviews : {encoded_reviews}")

encoded_reviews : [[33, 24, 28], [49, 23], [27, 11], [32, 28], [49, 28], [12], [12, 25], [33], [12, 7], [44, 36, 26, 27]]


In [9]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[33 24 28  0]
 [49 23  0  0]
 [27 11  0  0]
 [32 28  0  0]
 [49 28  0  0]
 [12  0  0  0]
 [12 25  0  0]
 [33  0  0  0]
 [12  7  0  0]
 [44 36 26 27]]


In [27]:
model = Sequential()
embedding_layer = Embedding(input_dim=vocab_size, output_dim=8, input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.fit(padded_reviews, labels, epochs=100, verbose=0)