In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [6]:
reviews = ["Never coming back", "horrible service", "rude waitress", "cold food", "horrible food",
           "awesome", "awesome services!", "rocks", "poor work", "couldn\'t have done better"]

labels = [1 for i in range(5)] + [0 for i in range(5)]   # [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

In [8]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(f"encoded_reviews : {encoded_reviews}")

encoded_reviews : [[33, 24, 28], [49, 23], [27, 11], [32, 28], [49, 28], [12], [12, 25], [33], [12, 7], [44, 36, 26, 27]]


In [9]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[33 24 28  0]
 [49 23  0  0]
 [27 11  0  0]
 [32 28  0  0]
 [49 28  0  0]
 [12  0  0  0]
 [12 25  0  0]
 [33  0  0  0]
 [12  7  0  0]
 [44 36 26 27]]
