In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

large_width = 500
np.set_printoptions(linewidth=large_width)

In [2]:
cols = ["area","perimeter","compactness","kernel_length","kernel_width","asym_coeff","groove_length"]
seeds = pd.read_csv("seeds_dataset.csv", names=cols)
seeds.info()
seeds.head(3)

<class 'pandas.core.frame.DataFrame'>
Float64Index: 210 entries, 15.26 to 12.3
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   area           210 non-null    float64
 1   perimeter      210 non-null    float64
 2   compactness    210 non-null    float64
 3   kernel_length  210 non-null    float64
 4   kernel_width   210 non-null    float64
 5   asym_coeff     210 non-null    float64
 6   groove_length  210 non-null    int64  
dtypes: float64(6), int64(1)
memory usage: 13.1 KB


area  perimeter  compactness  kernel_length  kernel_width  asym_coeff  \
15.26  14.84     0.8710        5.763          3.312         2.221       5.220   
14.88  14.57     0.8811        5.554          3.333         1.018       4.956   
14.29  14.09     0.9050        5.291          3.337         2.699       4.825   

       groove_length  
15.26              1  
14.88              1  
14.29              1

In [3]:
features = seeds[["area","perimeter","compactness","kernel_length","kernel_width","asym_coeff"]]
labels = seeds[["groove_length"]]

features.shape, labels.shape

((210, 6), (210, 1))

In [4]:
# Since features are distributed with different ranges, we need to scale them.
scaler = MinMaxScaler()
features = scaler.fit_transform(features)

In [5]:
pd.DataFrame(features).describe().round(3)

0        1        2        3        4        5
count  210.000  210.000  210.000  210.000  210.000  210.000
mean     0.444    0.571    0.411    0.448    0.382    0.438
std      0.270    0.214    0.249    0.269    0.195    0.242
min      0.000    0.000    0.000    0.000    0.000    0.000
25%      0.215    0.443    0.205    0.224    0.234    0.259
50%      0.395    0.593    0.352    0.433    0.368    0.347
75%      0.683    0.723    0.609    0.664    0.521    0.669
max      1.000    1.000    1.000    1.000    1.000    1.000

In [6]:
np.unique(labels, return_counts=True)

(array([1, 2, 3], dtype=int64), array([70, 70, 70], dtype=int64))

In [7]:
X = np.round(features[:1], 5)
X = X.reshape(-1, 1)

y = labels
X, X.shape

(array([[0.50207],
        [0.57078],
        [0.48649],
        [0.4861 ],
        [0.1893 ],
        [0.34515]]),
 (6, 1))

##### Creating a network : 4-layers (input, hidden1, hidden2, output)

In [11]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [43]:
np.random.seed(2023)

num_z2_neurons, num_z3_neurons, num_s_neurons = 2, 2, 1

# input layer
a1 = X

# First hidden layer
w_1 = np.random.rand(num_z2_neurons, a1.shape[0])
b_1 = np.random.rand(num_z2_neurons, 1)
z2 = np.dot(w_1, a1) + b_1
a2 = sigmoid(z2)

# Second hidden layer
w_2 = np.random.rand(num_z3_neurons, a2.shape[0])
b_2 = np.random.rand(num_z3_neurons, 1)
z3 = np.dot(w_2, a2) + b_2
a3 = sigmoid(z3)

# Output layer
w_3 = np.random.rand(num_s_neurons, a3.shape[0])
b_3 = np.random.rand(num_s_neurons, 1)
s = np.dot(w_3, a3) + b_3
s = s[0][0]

print(a1.shape, w_1.shape, b_1.shape, z2.shape, a2.shape)
print(w_2.shape, b_2.shape, z3.shape, a3.shape)
print(w_3.shape, b_3.shape, s.shape)


(6, 1) (2, 6) (2, 1) (2, 1) (2, 1)
(2, 2) (2, 1) (2, 1) (2, 1)
(1, 2) (1, 1) ()


In [24]:
print(a1)
print()
print(w_1)
print()
print(z2)
print()
print(a2)

[[0.50207]
 [0.57078]
 [0.48649]
 [0.4861 ]
 [0.1893 ]
 [0.34515]]

[[0.3219883  0.89042245 0.58805226 0.12659609 0.14134122 0.46789559]
 [0.02208966 0.72727471 0.52438734 0.54493524 0.45637326 0.50138226]]

[[1.60023451]
 [1.35682248]]

[[0.83205116]
 [0.79524278]]


In [31]:
for i, row in enumerate(w_1):
    sum = 0
    for j, col in enumerate(row):
        sum += col * a1[j]
    sum += b_1[i]
    print(sum, end=', ')
    print(sigmoid(sum))    

[1.60023451], [0.83205116]
[1.35682248], [0.79524278]


In [42]:
print(s)

0.8375065011628657
